# Generated by Django 5.0 on 2024-06-14 18:46

import Owner.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


from cloud_storages.backends.appwrite import AppWriteStorage


custom_storage = AppWriteStorage()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('license', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField(validators=[Owner.models.phoneNoLength], verbose_name='phone no.')),
                ('image', models.ImageField(blank=True, default='restaurant.jpg', null=True, storage=custom_storage)),
                ('veg', models.BooleanField(default=True)),
                ('temporary_close', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='Address.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rating', models.PositiveSmallIntegerField(default=0)),
                ('no_of_ratings', models.PositiveSmallIntegerField(default=0)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='Owner.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='defaultItemImage.jpeg', null=True, storage=custom_storage)),
                ('is_veg', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='Owner.cuisine')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='Owner.restaurant')),
            ],
        ),
    ]
