# Generated by Django 5.0 on 2024-06-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='Address.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
