# Generated by Django 5.0 on 2024-06-14 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0002_deliverylocation'),
        ('Owner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ordered', 'Waiting for Restaurant to Accept.'), ('preparing', 'Restaurant is Preparing Order.'), ('prepared', 'Order is Ready for delivery.'), ('delivering', 'Rider is on the way to deliver.'), ('delivered', 'Order has been delivered.'), ('by_customer', 'Customer cancelled the Order.'), ('restaurant_rejected', 'Order cancelled! Restaurant rejected Order.'), ('out_of_stock', 'Order cancelled! Restaurant went Out Of Stock.'), ('accident', 'Order cancelled! Due to Accident.')], default='ordered', max_length=100)),
                ('payment_mode', models.CharField(choices=[('online', 'Payment via Online Mode'), ('cod', 'Payment via Cash (Cash On Delivery)')], max_length=50)),
                ('item_amount', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('rated', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.deliverylocation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Owner.restaurant')),
            ],
            options={
                'ordering': ('-order_date',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='Customer.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('isPaid', models.BooleanField(default=False)),
                ('payment_time', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.order')),
            ],
        ),
    ]
